name: SoftionPro PWA CI/CD Workflow

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*
  pull_request:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Obtenemos el código fuente del repositorio
      - name: Checkout Código
        uses: actions/checkout@v4.2.1
      # Configuramos el entorno de Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          # Versión de Node.js
          node-version: '14'
      # Instalamos las dependencias definidas en package.json
      - name: Instalar Dependencias
        run: npm install
      # Cachear los módulos instalados para evitar volver a instalarlos
      # en futuras ejecuciones
      - name: Configurar Caché
        uses: actions/cache@v2
        with:
          # Ruta del directorio que se va a cachear
          path: ~/.npm
          # Llave única para identificar el caché
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Comentar en PR
        uses: actions/github-script@v4
        with:
          script: |
            const { context, github } = require('@actions/github');
            const token = process.env.GITHUB_TOKEN;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Se han realizado cambios en este PR. Por favor, revisen.',
              headers: {
                authorization: `token ${token}`
              }
            })
            
  notify-on-success:
    runs-on: ubuntu-latest
    needs: [setup]
    if: needs.setup.result == 'success'
    steps:
      # Enviamos un correo electrónico a mi cuenta
      - name: Notificar Exito
        uses: softprops/gmail@v1
        with:
          from: ${{ secrets.GMAIL_ADDRESS }}
          to: ${{ secrets.GMAIL_ADDRESS_RECIPIENT }}
          subject: El repositorio ha pasado las pruebas correctamente.
          body: El repositorio ha superado las pruebas correctamente. Puedes ver los detalles en https://github.com/${{ github.repository }}/actions?query=workflow%3A${{ github.workflow }}+event%3A${{ github.event_name }}
  notify-on-failure:
    runs-on: ubuntu-latest
    needs: [setup]
    if: needs.setup.result == 'failure'
    steps:
      # Enviamos un correo electrónico a mi cuenta
      - name: Notificar Error
        uses: softprops/gmail@v1
        with:
          from: ${{ secrets.GMAIL_ADDRESS }}
          to: ${{ secrets.GMAIL_ADDRESS_RECIPIENT }}
          subject: El repositorio ha fallado en las pruebas.
          body: El repositorio ha fallado en las pruebas. Puedes ver los detalles en https://github.com/${{ github.repository }}/actions?query=workflow%3A${{ github.workflow }}+event%3A${{ github.event_name }}
