name: SoftionPro PWA CI/CD Workflow

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*
  pull_request:
    branches:
      - main
      - develop
      - feature/*
      - hotfix/*
jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      # Obtenemos el código fuente del repositorio
      - name: Checkout Código
        uses: actions/checkout@v4.2.1
      # Configuramos el entorno de Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          # Versión de Node.js
          node-version: '14'
      # Instalamos las dependencias definidas en package.json
      - name: Instalar Dependencias
        run: npm install
      # Cachear los módulos instalados para evitar volver a instalarlos
      # en futuras ejecuciones
      - name: Configurar Caché
        uses: actions/cache@v2
        with:
          # Ruta del directorio que se va a cachear
          path: ~/.npm
          # Llave única para identificar el caché
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Comentar en PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.payload.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Se han realizado cambios en este PR. Por favor, revisen.'
            })

  test:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      # Obtenemos el código fuente del repositorio
      - name: Checkout Código
        uses: actions/checkout@v4.2.1
      # Configuramos el entorno de Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          # Versión de Node.js
          node-version: '14'
      # Instalamos las dependencias definidas en package.json
      - name: Instalar Dependencias
        run: npm install
      
      # Intalamos las dependencias para las pruebas con TestCafe
      - name: Instalar Dependencias para TestCafe
        run: npm install -g testcafe

      # en futuras ejecuciones
      - name: Configurar Caché
        uses: actions/cache@v2
        with:
          # Ruta del directorio que se va a cachear
          path: ~/.npm
          # Llave única para identificar el caché
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      # Ejecutamos las pruebas
      - name: Ejecutar Pruebas
        run: npm run test
        
  Deploy-Preview:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
  
  Deploy-Production:
    runs-on: ubuntu-latest
    needs: [Deploy-Preview]
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
  

  notify-on-success:
    runs-on: ubuntu-latest
    needs: [test, Deploy-Preview, Deploy-Production]
    if: always() && (needs.test.result == 'success' || needs.Deploy-Preview.result == 'success' || needs.Deploy-Production.result == 'success')
    steps:
      - name: Notificar éxito
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_ADDRESS }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: El repositorio ha pasado las pruebas correctamente.
          body: El repositorio ha superado las pruebas correctamente. Puedes ver los detalles en https://github.com/${{ github.repository }}/actions?query=workflow%3A${{ github.workflow }}+event%3A${{ github.event_name }}
          to: ${{ secrets.GMAIL_ADDRESS_RECIPIENT }}
          from: ${{ secrets.GMAIL_ADDRESS }}

          
  notify-on-failure:
    runs-on: ubuntu-latest
    if: failure()
    steps:
      # Enviamos un correo electrónico a mi cuenta
      - name: Notificar Error
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GMAIL_ADDRESS }}
          password: ${{ secrets.GMAIL_APP_PASSWORD }}
          subject: "El job ${needs.test.result == 'failure' ? 'test' : needs.Deploy-Preview.result == 'failure' ? 'Deploy-Preview' : 'Deploy-Production'} ha fallado."
          body: "El job ${needs.test.result == 'failure' ? 'test' : needs.Deploy-Preview.result == 'failure' ? 'Deploy-Preview' : 'Deploy-Production'} ha fallado. Puedes ver los detalles en https://github.com/${{ github.repository }}/actions?query=workflow%3A${{ github.workflow }}+event%3A${{ github.event_name }}"
          to: ${{ secrets.GMAIL_ADDRESS_RECIPIENT }}
          from: ${{ secrets.GMAIL_ADDRESS }}
  

